//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiSharedMemory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produit
    {
        public int idProduit { get; set; }
        public string CodeProduit { get; set; }
        public string DesignationProduit { get; set; }
        public Nullable<double> PU { get; set; }
        public Nullable<int> QteMin { get; set; }
        public Nullable<int> QteCri { get; set; }
        public string CodeCategorie { get; set; }
    }
}
